[project]
name = "laya-server"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "accelerate>=1.15.0",
    "fastapi>=0.142.2",
    "laya[serve]>=0.3.20",
    "sentencepiece>=0.2.2",
    "tiktoken>=0.14.0",
    "torch>=2.14.1",
    "transformers>=5.18.0",
    "uvicorn>=0.54.0",
]
